Update: added volumes to compose file

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -92,6 +92,7 @@ jobs:
           tags: |
             ${{ secrets.DOCKER_HUB_USERNAME }}/floorplan:staging-${{ github.sha }}
             ${{ secrets.DOCKER_HUB_USERNAME }}/floorplan:latest
+          no-cache: true
   deploy:
     needs: build-and-push-image
     runs-on: ubuntu-latest
@@ -119,10 +120,12 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            set -e
+            set -e  # Exit immediately if a command exits with a non-zero 
 
+            echo "Logging in to Docker Hub..."
             echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
 
+            echo "Changing to project directory..."
             cd /home/ubuntu/floorplan/
             # Ensure scripts are executable (in case they are not already)
             chmod +x install_docker.sh
